CREATE TABLE IF NOT EXISTS ?tableName (
  CODPAIS VARCHAR(2) DISTKEY,
  CODPROGRAMA VARCHAR(6),
  CODNIVEL VARCHAR(2),
  TIPOVALOR VARCHAR(4),
  CODRANGO SMALLINT,
  PORCOMISION DECIMAL(15,5),
  MONTOINI DECIMAL(15,5),
  MONTOFIN DECIMAL(15,5),
  PRIMARY KEY(CODPROGRAMA, CODNIVEL, TIPOVALOR, CODRANGO)
) SORTKEY(CODPROGRAMA)
