INSERT INTO ?tableName
SELECT
  PT_COUNTRY,
  CODPROGRAMA,
  CODNIVEL,
  TIPOVALOR,
  CAST(CODRANGO AS SMALLINT),
  CAST(PORCCOMISION AS DECIMAL(15,5)),
  CAST(MONTOINI AS DECIMAL(15,5)),
  CAST(MONTOFIN AS DECIMAL(15,5))
FROM ?landingSchema.tbpq_sicc_dletsrangoscomision
WHERE PT_COUNTRY = :country
