CREATE TABLE IF NOT EXISTS ?tableName (
  CODPAIS VARCHAR(2),
  DESCRIPCIONPAIS VARCHAR(MAX),
  CODPAISDM VARCHAR(2),
  CODCENTRO VARCHAR(4),
  NROCAMPANAS SMALLINT,
  DESPAIS VARCHAR(MAX),
  PRIMARY KEY(CODPAIS)
)
SORTKEY(CODPAIS)
