INSERT INTO ?tableName
SELECT
  CODPAIS,
  null AS DESCRIPCIONPAIS,
  null AS CODPAISDM,
  null AS CODCENTRO,
  0 AS NROCAMPANAS, --CAST(NROCAMPANAS AS SMALLINT),
  DESPAIS
FROM ?landingSchema.tbpq_bi_dpais
