CREATE TABLE IF NOT EXISTS ?tableName (
  ANIOCAMPANAWEB VARCHAR(6),
  CODEBELISTA VARCHAR(10),
  IPORIGEN VARCHAR(MAX),
  FECHAHORA TIMESTAMP,
  CORREOVALIDADO SMALLINT,
  CODPAIS VARCHAR(2) DISTKEY,
  PRIMARY KEY(ANIOCAMPANAWEB, CODEBELISTA)
) COMPOUND SORTKEY(
  ANIOCAMPANAWEB,
  CODEBELISTA
)
