INSERT INTO ?tableName
SELECT 
  ANIOCAMPANA,
  CODEBELISTA,
  IPORIGEN,
  CAST(FECHAHORA AS TIMESTAMP),
  CAST(CORREOVALIDADO AS SMALLINT),
  PT_COUNTRY
FROM ?landingSchema.tbpq_digital_flogingresoportal
WHERE PT_COUNTRY = :country
  AND ANIOCAMPANA IN (:campaign)
  AND CODEBELISTA IS NOT NULL
