CREATE TABLE IF NOT EXISTS ?tableName (
  ANIOCAMPANA VARCHAR(6),
  CODGERENTEREGIONAL VARCHAR(10),
  CODGERENTEZONA VARCHAR(10),
  CODLIDER VARCHAR(10),
  CODREGION VARCHAR(3),
  CODSECCION VARCHAR(7),
  CODTERRITORIO VARCHAR(10),
  CODZONA VARCHAR(6),
  DESREGION VARCHAR(MAX),
  DESZONA VARCHAR(MAX),
  CODPAIS VARCHAR(2) DISTKEY,
  DESPAIS VARCHAR(MAX),
  DESDEPARTAMENTO VARCHAR(MAX),
  DESCIUDAD VARCHAR(MAX),
  DESDISTRITO VARCHAR(MAX),
  DESNIVELSOCIA VARCHAR(MAX),
  DESRENDIMIENTOSOCIA VARCHAR(MAX),
  DESLIDER VARCHAR(MAX),
  DESGERENTEREGIONAL VARCHAR(MAX),
  DESGERENTEZONA VARCHAR(MAX),
  PRIMARY KEY(CODTERRITORIO)
) COMPOUND SORTKEY(
  ANIOCAMPANA,
  CODTERRITORIO
)
