INSERT INTO ?tableName
SELECT
  ANIOCAMPANA,
  CAST(CANTIDAD AS BIGINT),
  CODEBELISTA,
  CODVENTA,
  TIPOOFERTAFINAL,
  TO_TIMESTAMP(FECHA, 'YYYYMMDD HH24:MI:SS'),
  CAST(GAP AS DECIMAL(15,5)),
  TIPOEVENTO,
  PT_COUNTRY
FROM ?landingSchema.tbpq_digital_fofertafinalconsultora
WHERE PT_COUNTRY = :country
  AND ANIOCAMPANA IN (:campaign)
  AND ANIOCAMPANA IS NOT NULL
  AND CODEBELISTA IS NOT NULL
  AND CODVENTA IS NOT NULL
