CREATE TABLE IF NOT EXISTS ?tableName (
  ANIOCAMPANA VARCHAR(6),
  CODACCESO VARCHAR(5),
  CODCANALVENTA VARCHAR(2),
  CODEBELISTA VARCHAR(10),
  CODTERRITORIO VARCHAR(10),
  CODTIPODOCUMENTO VARCHAR(1),
  FLAGORDENANULADO SMALLINT,
  FLAGPROL SMALLINT,
  REALVTAMNFACTURA DECIMAL(15,5),
  SALDOBANCO DECIMAL(15,5),
  CANALINGRESO VARCHAR(3),
  FECHAEMISIONFACTURA TIMESTAMP,
  NROFACTURA VARCHAR(11),
  CODPAIS VARCHAR(2) DISTKEY,
  PRIMARY KEY(ANIOCAMPANA, NROFACTURA, CODEBELISTA)
) COMPOUND SORTKEY(
  ANIOCAMPANA,
  NROFACTURA,
  CODEBELISTA
)
