INSERT INTO ?tableName
SELECT
  ANIOCAMPANA,
  CODACCESO,
  CODCANALVENTA,
  CODEBELISTA,
  CODTERRITORIO,
  CODTIPODOCUMENTO,
  CAST(FLAGORDENANULADO AS SMALLINT),
  CAST(FLAGPROL AS SMALLINT),
  CAST(REALVTAMNFACTURA AS DECIMAL(15,5)),
  CAST(SALDOBANCO AS DECIMAL(15,5)),
  CANALINGRESO,
  TO_DATE(
    CAST(FECHAEMISIONDOCUMENTO AS VARCHAR),
    'YYYYMMDD'
  ),
  NRODOCUMENTO,
  PT_COUNTRY
FROM ?landingSchema.tbpq_sicc_dnrodocumento
WHERE PT_COUNTRY = :country
  AND ANIOCAMPANA IN (:campaign)
