INSERT INTO ?tableName
SELECT
  ANIOCAMPANA,
  CODREGION,
  CODZONA,
  CAST(FLAGSTATUSFACTSC AS BIGINT),
  CURRENT_DATE,
  PT_COUNTRY
FROM ?landingSchema.tbpq_sicc_dstatusf
WHERE PT_COUNTRY = :country
  AND ANIOCAMPANA IN (:campaign)
