INSERT INTO ?tableName
SELECT
  PT_COUNTRY,
  ANIOCAMPANA,
  CODREGION,
  CODZONA,
  CODACTIVIDAD,
  DESACTIVIDAD,
  TO_DATE(CAST(FECHA AS VARCHAR), 'YYYYMMDD'),
  CAST(NUMDIA AS BIGINT)
FROM ?landingSchema.tbpq_sicc_dtiempoactividadzona
WHERE PT_COUNTRY = :country
