INSERT INTO ?tableName
SELECT
  ANIOCAMPANA,
  CAST(CANTIDAD AS BIGINT),
  CODEBELISTA,
  CODVENTA,
  TO_DATE(CAST(FECHACREACION AS VARCHAR), 'YYYYMMDD'),
  CAST(FLAGOFERTAWEB AS SMALLINT),
  CAST(FLAGPROCESADO AS SMALLINT),
  CAST(IMPORTETOTAL AS DECIMAL(15,5)),
  CAST(ORDENPEDIDOWD AS BIGINT),
  CAST(ORIGENPEDIDOWEB AS BIGINT),
  CAST(PEDIDODETALLEID AS INTEGER),
  CAST(PEDIDOID AS INTEGER)
  PT_COUNTRY
FROM ?landingSchema.tbpq_digital_fpedidowebdetalle
WHERE PT_COUNTRY = :country
  AND ANIOCAMPANA IN (:campaign)
