CREATE TABLE IF NOT EXISTS ?tableName (
  CODPAIS VARCHAR(2) DISTKEY,
  CODCANALVENTA VARCHAR(2),
  ANIOCAMPANA VARCHAR(6),
  REALTCPROMEDIO DECIMAL(15,5),
  PEDIDOMINMN BIGINT,
  REALNROCLIENTES BIGINT,
  REALNROPEDIDOS BIGINT,
  REALNROORDENCOMPRA BIGINT,
  PRIMARY KEY(ANIOCAMPANA)
) SORTKEY(ANIOCAMPANA)
