CREATE TABLE IF NOT EXISTS ?tableName (
  CODPAIS VARCHAR(2) DISTKEY,
  CODCANALVENTA VARCHAR(2),
  ANIOCAMPANA VARCHAR(6),
  REALTCPROMEDIO DECIMAL(15,5),
  PEDIDOMINMN BIGINT,
  REALNROCLIENTES BIGINT,
  REALNROPEDIDOS BIGINT,
  REALNROORDENCOMPRA BIGINT,
  REALVTAMNNETOTOTAL DECIMAL(15,5),
  REALVTAMNCATALOGOTOTAL DECIMAL(15,5),
  REALNROACTIVASTOTAL BIGINT,
  ESTNROPEDIDOS INTEGER,
  ESTTCPROMEDIO DECIMAL(15,5),
  TCCOSTO DECIMAL(15,5),
  PROMORDENESXPED DECIMAL(15,5),
  PRIMARY KEY(ANIOCAMPANA)
) SORTKEY(ANIOCAMPANA)
