INSERT INTO ?tableName
SELECT
  PT_COUNTRY,
  CODCANALVENTA,
  ANIOCAMPANA,
  CAST(REALTCPROMEDIO AS DECIMAL(15,5)),
  CAST(CAST(PEDIDOMINMN AS DECIMAL(15,5)) AS BIGINT),
  CAST(REALNROCLIENTES AS BIGINT),
  CAST(REALNROPEDIDOS AS BIGINT),
  CAST(REALNROORDENES AS BIGINT)
FROM ?landingSchema.tbpq_sicc_fnumpedcam
WHERE PT_COUNTRY = :country
