INSERT INTO ?tableName
SELECT
  PT_COUNTRY,
  CAST(CODSTATUS AS SMALLINT),
  DESSTATUS,
  CAST(CODSTATUSCORP AS SMALLINT),
  DESSTATUSCORP,
  CAST(CODSTATUS_SICC AS SMALLINT),
  DESSTATUS_SICC
FROM ?landingSchema.tbpq_bi_dstatus
WHERE PT_COUNTRY = :country
