CREATE TABLE IF NOT EXISTS ?tableName (
  CODPAIS VARCHAR(2) DISTKEY,
  CODCOMPORTAMIENTO SMALLINT,
  DESNIVELCOMPORTAMIENTO VARCHAR(MAX),
  DESCOMPORTAMIENTO VARCHAR(30),
  DESABRCOMPORTAMIENTO VARCHAR(15),
  FLAGPERIODO SMALLINT,
  PRIMARY KEY (CODCOMPORTAMIENTO)
) SORTKEY(CODCOMPORTAMIENTO)
