INSERT INTO ?tableName
SELECT
  CODVERSION,
  DESVERSION,
  TO_DATE(FECHAVERSIONAMIENTO, 'YYYYMMDD'),
  CODCANALVENTA,
  CAST(ANIOCONTABLE AS INTEGER),
  ANIOCAMPANA,
  CAST(MES AS SMALLINT),
  CODPRODUCTO,
  CODTIPOOFERTA,
  CAST(ESTUUVENDIDAS AS INTEGER),
  CAST(ESTVTAMNNETO AS DECIMAL(18,3)),
  CAST(ESTVTADOLNETO AS DECIMAL(18,3)),
  CAST(ESTPUP AS DECIMAL(18,4)),
  CAST(ESTUTILIDAD AS DECIMAL(18,3)),
  CAST(PRECIOOFERTAMN AS DECIMAL(18,3)),
  CAST(PRECIOOFERTADOL AS DECIMAL(18,3)),
  CAST(PRECIONORMALMN AS DECIMAL(18,3)),
  CAST(PRECIONORMALDOL AS DECIMAL(18,3)),
  DEMANDAANORMAL,
  PT_COUNTRY
FROM ?landingSchema.tbpq_planit_fvtaprocammes
WHERE ANIOCAMPANA IN (:campaign)
