CREATE TABLE IF NOT EXISTS ?tableName(
  ORIGENPEDIDOWEB INTEGER,
  DESORIGENPEDIDOWEB VARCHAR(MAX),
  CODPOPUP BIGINT,
  DESPOPUP VARCHAR(MAX),
  FLAGPERSONALIZACION SMALLINT,
  CODZONA BIGINT,
  DESZONA VARCHAR(MAX),
  CODMEDIO BIGINT,
  DESMEDIO VARCHAR(MAX),
  CODSECCION BIGINT,
  DESSECCION VARCHAR(MAX),
  CODPAIS VARCHAR(2) DISTKEY,
  PRIMARY KEY(ORIGENPEDIDOWEB)
) SORTKEY(ORIGENPEDIDOWEB)
