CREATE TABLE IF NOT EXISTS ?tableName (
  CODCANALVENTA VARCHAR(2),
  CODTIPOOFERTA VARCHAR(4),
  ABRTIPOOFERTA VARCHAR(MAX),
  DESTIPOOFERTA VARCHAR(MAX),
  CODSUBGRUPOTO1 VARCHAR(2),
  DESSUBGRUPOTO1 VARCHAR(MAX),
  CODSUBGRUPOTO2 VARCHAR(2),
  DESSUBGRUPOTO2 VARCHAR(MAX),
  DESTIPOPROFIT VARCHAR(MAX),
  CODTIPOPROFIT VARCHAR(2),
  CODPAIS VARCHAR(2) DISTKEY,
  PRIMARY KEY(CODCANALVENTA, CODTIPOOFERTA)
) SORTKEY(CODTIPOOFERTA)


