INSERT INTO ?tableName
SELECT
  CODCANALVENTA,
  CODTIPOOFERTA,
  ABRTIPOOFERTA,
  DESTIPOOFERTA,
  CODSUBGRUPOTO1,
  DESSUBGRUPOTO1,
  CODSUBGRUPOTO2,
  DESSUBGRUPOTO2,
  DESTIPOPROFIT,
  CODTIPOPROFIT,
  PT_COUNTRY
FROM ?landingSchema.tbpq_planit_dtipooferta
WHERE PT_COUNTRY = :country
