CREATE TABLE IF NOT EXISTS ?tableName (
  CODPAIS VARCHAR(2) DISTKEY,
  ANIOCAMPANA VARCHAR(6),
  CODVENTAAPOYADOR VARCHAR(5),
  CODTIPOOFERTAAPOYADOR VARCHAR(3),
  CODSAPAPOYADOR CHAR(18),
  CODCANALVENTAAPOYADOR VARCHAR(2),
  CODVENTAAPOYADO VARCHAR(5),
  CODTIPOOFERTAAPOYADO VARCHAR(3),
  CODSAPAPOYADO CHAR(18),
  CODCANALVENTAAPOYADO VARCHAR(2),
  PRIMARY KEY(
    ANIOCAMPANA,
    CODVENTAAPOYADOR,
    CODTIPOOFERTAAPOYADOR,
    CODSAPAPOYADOR,
    CODCANALVENTAAPOYADOR,
    CODVENTAAPOYADO,
    CODTIPOOFERTAAPOYADO,
    CODSAPAPOYADO,
    CODCANALVENTAAPOYADO
  )
) COMPOUND SORTKEY(
  ANIOCAMPANA,
  CODVENTAAPOYADOR,
  CODTIPOOFERTAAPOYADOR,
  CODSAPAPOYADOR,
  CODCANALVENTAAPOYADOR,
  CODVENTAAPOYADO,
  CODTIPOOFERTAAPOYADO,
  CODSAPAPOYADO,
  CODCANALVENTAAPOYADO
)
