CREATE TABLE IF NOT EXISTS ?tableName (
  CODPAIS VARCHAR(2) DISTKEY,
  ANIOCAMPANA VARCHAR(6),
  CODVENTAAPOYADOR VARCHAR(5),
  CODTIPOOFERTAAPOYADOR VARCHAR(3),
  CODPRODUCTOAPOYADOR CHAR(18),
  CODCANALVENTAAPOYADOR VARCHAR(2),
  CODVENTAAPOYADO VARCHAR(5),
  CODTIPOOFERTAAPOYADO VARCHAR(3),
  CODPRODUCTOAPOYADO CHAR(18),
  CODCANALVENTAAPOYADO VARCHAR(2),
  PRIMARY KEY(
    ANIOCAMPANA,
    CODVENTAAPOYADOR,
    CODTIPOOFERTAAPOYADOR,
    CODPRODUCTOAPOYADOR,
    CODCANALVENTAAPOYADOR,
    CODVENTAAPOYADO,
    CODTIPOOFERTAAPOYADO,
    CODPRODUCTOAPOYADO,
    CODCANALVENTAAPOYADO
  )
) COMPOUND SORTKEY(
  ANIOCAMPANA,
  CODVENTAAPOYADOR,
  CODTIPOOFERTAAPOYADOR,
  CODPRODUCTOAPOYADOR,
  CODCANALVENTAAPOYADOR,
  CODVENTAAPOYADO,
  CODTIPOOFERTAAPOYADO,
  CODPRODUCTOAPOYADO,
  CODCANALVENTAAPOYADO
)
